# --- Generated by Data_buddy ---
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("expenses.csv", names=["Values"])
print("📊 Data Summary:")
print(df.describe())

df.plot(kind="line", title="Analysis Trend")
plt.show()
