
# --- Generated by Data_buddy ---
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('expenses.csv', names=['Values'])
print("📊 Data Summary:")
print(df.describe())

df.plot(kind='line', title='Analysis Trend')
plt.show()
