import statistics
import math

# --- PART 1: Core Mathematical Tools ---
def get_average(numbers):
    return sum(numbers) / len(numbers) if numbers else 0

def get_median(numbers):
    return statistics.median(numbers) if numbers else 0

def get_min(numbers):
    return min(numbers) if numbers else 0

def get_max(numbers):
    return max(numbers) if numbers else 0

def get_mode(numbers):
    if not numbers: return 0
    try: return statistics.mode(numbers)
    except: return "No unique mode"

def add(a, b): return a + b
def sub(a, b): return a - b
def mul(a, b): return a * b
def div(a, b): return a / b if b != 0 else "Error: Div by Zero"
def power(base, exp): return base ** exp
def sqrt(n): return math.sqrt(n) if n >= 0 else "Error: Negative Root"

# --- PART 2: The No-Code Analyst Engine ---
def run_no_code_analysis(filename):
    """Provides a quick business report for non-coders."""
    try:
        with open(filename, 'r') as file:
            data = [float(line.strip()) for line in file if line.strip()]
        if not data:
            print("❌ Error: File is empty.")
            return
        print(f"\n--- 📈 Business Report for {filename} ---")
        print(f"Total Entries: {len(data)}")
        print(f"Average Value: {sum(data)/len(data):.2f}")
        print(f"Peak Value:    {max(data)}")
    except Exception as e:
        print(f"❌ Error: {e}")

def generate_notebook_code(filename):
    """Generates professional code for Jupyter Notebooks."""
    print(f"📝 Generating high-precision code for: {filename}...")
    code_template = f"""
# --- Generated by Data_buddy ---
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('{filename}', names=['Values'])
print("📊 Data Summary:")
print(df.describe())

df.plot(kind='line', title='Analysis Trend')
plt.show()
"""
    with open("generated_analysis.py", "w", encoding="utf-8") as f:
        f.write(code_template)
    print(f"✨ Success! Your code is saved in: generated_analysis.py")

import matplotlib.pyplot as plt

def create_visual_report(filename):
    """Generates and saves a visual chart of the data."""
    try:
        with open(filename, 'r') as file:
            data = [float(line.strip()) for line in file if line.strip()]
        
        if not data:
            print("❌ Error: No data for visualization.")
            return

        # Initialize the figure canvas
        plt.figure(figsize=(10, 5))
        
        # Draw a trend line and volume bars
        plt.plot(data, marker='o', linestyle='-', color='b', label='Data Trend')
        plt.bar(range(len(data)), data, alpha=0.3, color='g', label='Volume')
        
        # Add professional labeling
        plt.title(f"Visual Analysis Report: {filename}")
        plt.xlabel("Entry Number")
        plt.ylabel("Value")
        plt.legend()
        plt.grid(True, linestyle='--', alpha=0.6)
        
        # Save the visualization to a file
        output_image = "business_chart.png"
        plt.savefig(output_image)
        plt.close()
        print(f"🖼️  Chart successfully saved as: {output_image}")

    except Exception as e:
        print(f"❌ Visualization Error: {e}")
